name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code (including files stored in LFS)
      uses: nschloe/action-cached-lfs-checkout@v1
    - name: Install newest toolchain
      run: rustup update stable && rustup default stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
